kuka_ik_solver:
  type: ik_solver/KukaIkSolver
  base_frame: base # base frame of the chain
  flange_frame: flange # end frame of the chain

  tool_frame: flange # destination frame of the IK (it should be rigid attached to flange_frame)
  desired_solutions: 32 # number of desired solution
  joint_names:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
